import os
os.system("cls")
os.system("cls")
os.system("cmd")
os.system("color "+x+y)
os.system("mode con:cols=50 lines=20")
os.system("pause")
os.system("timeout02>>nul")
print("      ---Cmd Color Changer---")
print("      [+]---color menu---[+]\n")
print("---Developed By Sachira Madhushan---")
print("0 = Black       8 = Gray\n1 = Blue        9 = Light Blue\n2 = Green       A = Light Green\n3 = Aqua        B = Light Aqua\n4 = Red         C = Light Red\n5 = Purple      D = Light Purple\n6 = Yellow      E = Light Yellow\n7 = White       F = Bright White")
print("[+]Color Has Been Changed!")
print("\n\n\n")
x=input("[?]Enter Your Background Color :")
y=input("[?]Enter Your Font Color :")